import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Msc Jobs Master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="text-3xl text-center">Hey there</div> */}
      {/*Header*/}
      <Navbar />
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-[500px] flex flex-row mx-auto bg-[#1F5050]">
          <div className="m-8 border-r-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>
          <div className="m-4 mx-[130px] text-center grow">
            <div pt-12>
              <div className="text-xl font-bold text-white pt-16 ">
                MASTER ADMIN PANEL
              </div>
              <hr className="my-3 border-t-2 border-black" />
              <div className="mx-[30px] my-[30px]">
                {/* <div className="text-xl font-bold text-white">Login</div> */}
                <div>
                  <input
                    name="Email Id"
                    type="text"
                    placeholder="Email Id"
                    className="w-full h-6 px-3 my-1 text-sm border border-black"
                  />
                </div>
                <div>
                  <input
                    name="Password"
                    type="password"
                    placeholder="Password"
                    className="w-full h-6 px-3 my-1 text-sm border border-black"
                  />
                </div>
                <div>
                  <input
                    type="submit"
                    className="px-4 py-1 my-3 text-white bg-red-700 cursor-pointer rounded-xl"
                    value="Login"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
