import React, { useState, useEffect } from "react";
import Head from "next/head";
import Layout from "../layout";
import Link from "next/link";
import { useFormik } from "formik";
import * as Yup from "yup";
import { isAuthenticated, signin } from "../contexts/auth";
import Modal from "react-modal";
import { useRouter } from "next/router";

export default function Home() {
  const Router = useRouter();
  useEffect(() => {
    const isAuthenticate = isAuthenticated();
    if (isAuthenticate) {
      Router.push("/profile");
    }
  }, []);
  const [modalIsOpen, setIsOpen] = React.useState(false);
  function openModal() {
    setIsOpen(true);
  }
  function closeModal() {
    setIsOpen(false);
    Router.push("/profile");
  }
  const formik = useFormik({
    initialValues: {
      emailId: "",
      password: "",
    },
    validationSchema: Yup.object().shape({
      emailId: Yup.string().email("Invalid email Id").required("Required"),
      password: Yup.string()
        .min(3, "Too Short!")
        .max(32, "Too Long!")
        .required("Required"),
    }),
    onSubmit: async (values, { resetForm }) => {
      await signin(values, (result) => {
        console.log(result);
        if (result.token) {
          openModal();
        } else {
          alert("Wrong id and password");
        }
      });
    },
  });

  const customStyles = {
    content: {
      top: "50%",
      left: "50%",
      right: "auto",
      bottom: "auto",
      marginRight: "-50%",
      transform: "translate(-50%, -50%)",
      background: "#008BF3",
    },
  };

  return (
    <Layout>
      <Head>
        <title>Msc jobs master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-[500px] flex flex-row mx-auto bg-[#1F5050]">
          <div className="m-8 border-r-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>
          <div className="m-4 mx-[100px] text-center grow">
            <div className="pt-12">
              <div className="pt-16 text-xl font-bold text-white ">
                MASTER ADMIN PANEL
              </div>
              <hr className="my-3 border-t-2 border-black" />
              <div className="mx-[30px] my-[30px]">
                <form onSubmit={formik.handleSubmit}>
                  <div>
                    <input
                      name="emailId"
                      id="emailId"
                      type="text"
                      placeholder="Email Id"
                      className="w-full h-6 px-3 py-1 my-1 text-sm border border-black"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.emailId}
                    />
                    {formik.touched.emailId && formik.errors.emailId ? (
                      <div>{formik.errors.emailId}</div>
                    ) : null}
                  </div>
                  <div>
                    <input
                      name="password"
                      type="password"
                      placeholder="Password"
                      className="w-full h-6 px-3 py-1 my-1 text-sm border border-black"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.password}
                    />
                    {formik.touched.password && formik.errors.password ? (
                      <div>{formik.errors.password}</div>
                    ) : null}
                  </div>
                  <div>
                    <button
                      type="submit"
                      className="py-1 my-3 text-white bg-red-700 cursor-pointer px-7 rounded-xl"
                      value="submit"
                    >
                      Log In
                    </button>
                  </div>
                </form>
                <Modal
                  isOpen={modalIsOpen}
                  onRequestClose={closeModal}
                  style={customStyles}
                  contentLabel="User Logged In!"
                >
                  <div className="text-center text-white">
                    User Login successfull
                  </div>
                  <div className="px-9">
                    <button
                      className="px-auto w-[80px] mx-auto mt-8 text-white bg-red-600 rounded"
                      onClick={closeModal}
                    >
                      OK
                    </button>
                  </div>
                </Modal>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
