import React from "react";
import Navbar from "../components/Navbar";
import Head from "next/head";
import Link from "next/link";

const profile = () => {
  return (
    <div className="">
      <Head>
        <title>Msc Jobs Master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="h-screen grow bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-[200px] flex flex-row mx-auto bg-[#1F5050]">
          <div className="m-2">
            <Link href="/">
              <a className="flex flex-col items-center px-8 py-8 border-r-2 border-gray-700">
                <img src="/msc-logo.svg" className="h-[90px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>
          <div className="mt-2">
            <div className="">
              <div className="pt-7 m-4 mx-[130px] text-center grow text-xl font-bold text-white ">
                MASTER ADMIN PANEL
              </div>
            </div>
            <hr className="my-24 w-full border-t-2 border-gray-700" />
          </div>
        </div>
        <div className="w-[800px] h-[500px] mx-auto bg-[#1F5050]">
          {/* <hr className="my-24 w-full border-t-2 border-gray-700" /> */}
          <div className="w-[80%] grid grid-cols-2 gap-4 mx-auto text-center">
            <div>JOB POSTING</div>
            <div>JOB APPLICATION</div>
            <div>E-MAIL REQUEST</div>
            <div>CAREER TIPS</div>
            <div>PREMIUM SERVICE REQUEST</div>
            <div>EMPLOYER</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default profile;
