import React, { useEffect, useState } from "react";

import Layout from "../layout";
import Head from "next/head";
import { useFormik } from "formik";
import * as Yup from "yup";
import Cookies from "js-cookie";
import { api } from "./api";

const UpdateFrontMsg = () => {
  const formik = useFormik({
    initialValues: {
      msg: "",
    },
    validationSchema: Yup.object().shape({
      msg: Yup.string().required("Required"),
    }),
    onSubmit: async (values, { resetForm }) => {
      const updateFrontMessage = {
        _id: "627286de9d742ee221493410",
        msg: values.msg,
      };
      const token = Cookies.get("token");
      const userId = Cookies.get("userId");
      await api
        .put(`/marqueemsg/${userId}`, updateFrontMessage, {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
        })
        .then((response) => {
          console.log(response);
          alert("Message updated successfully");
          resetForm();
        })
        .catch((error) => {
          if (error.response) {
            console.log(error.response.data);
            console.log(error.response.status);
            console.log(error.response.headers);
          } else if (error.request) {
            // The request was made but no response was received
            console.log(error.request);
          } else {
            // Something happened in setting up the request that triggered an Error
            console.log("Error", error.message);
          }
        });
    },
  });

  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-auto text-center mx-auto bg-[#1F5050] py-[30px]">
          <div className="mb-10 text-3xl text-white">UPDATE FRONT MESSAGE</div>
          <form onSubmit={formik.handleSubmit}>
            <div className="px-auto">
              <input
                name="msg"
                id="msg"
                type="text"
                placeholder="Enter New Message"
                className="w-[50%] h-10 px-3 py-1 my-1 mx-auto text-sm border border-black"
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                value={formik.values.msg}
              />
              {formik.touched.msg && formik.errors.msg ? (
                <div>{formik.errors.msg}</div>
              ) : null}
            </div>
            <div className="mx-auto">
              <button
                type="submit"
                className="py-1 my-3 text-white bg-red-700 rounded cursor-pointer px-7"
                value="submit"
              >
                Log In
              </button>
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
};

export default UpdateFrontMsg;
